services:
  - type: web
    runtime: node
    name: clinical-decision-support-mcp
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CLAUDE_MODEL
        value: claude-3-haiku-20240307
      - key: PORT
        value: 5000
      - key: PO_ENV
        value: prod
